#pragma once
#include "IntersectionRayBatch.h"
#include "IntersectionBuffer.h"
#include "ShadowRayBatch.h"
#include "LightDataBuffer.h"
#include "PixelBuffer.h"
#include "ResultBuffer.h"
#include "../ReSTIRData.h"
#include "AtomicBuffer.h"